fix: resolves #152 (#156)
* anonymous auth bugfix

* Revert "anonymous auth bugfix"

This reverts commit 395dd2552e3aa4adc1d1ce570b8ddaf6baab8985.

* anon-auth bugfix

error: a player is signed in but with an invalid (empty) username, the exception causes a mismatch between UI state and backend state

fix: add a check for empty string so the error does not fall through

* fix: exiting submenu resumes the game

* fix: reloading weapons changes blades ON/OFF to ammo count

* fix: reset one player's ammo upon respawn resets other players' ammo too

* refix: reloading blades UI issue (supposing that blades have MaxAmmo at 0?)

* refix2: reloading blades UI issue (more robust solution)

* feat: select resolution

* start working on more robust resolution options

* fix: GraphicsParameters event listeners never get added

* integrate resolution logic in the for loop

* feat: resolution fully integrated into already established checks and functions

* todo and code snippets for display selection

* fix: system overrides saved resolution value from last time

* unify resolution and quality handling in OnGameSettingsDropdownValueChanged

* feat: implement displays logic in GraphicsParameters.cs, make resolution more readable

* feat: display selection, bloated, needs unifying with resolution later

* readability, formatting

* unify list handling in AddDropdown, add a helper function

* naming, readability

* add modified asset